name: Reusable workflow example

on:
  workflow_call:
    inputs:
      required-secret:
        description: 'A required secret'
        required: true

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use the secret
        run: echo "The required secret is ${{ secrets.required_secret }}"

      - name: Hello World
        run: echo "Hello, world!"
