name: Reusable Lab
on:
  workflow_call:
jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
    - name: Imprimir mensaje desde reusable-lab.yml
      run: echo "Este es un mensaje desde el flujo de trabajo reusable-lab.yml"
      
    - name: Validar secret
      env:
          TITLE: ${{ inputs.GITHUB }}
      run: |
        if [[ "$TITLE" =~ ^crnic ]]; then
        echo "Token Valido"
        exit 0
        else
        echo "Token INvalido"
        exit 1
        fi
        
