name: Reusable Lab
on:
  workflow_call:
    inputs:
      secreto-entrada: # Define el nombre de la entrada para el secreto
        description: 'Secreto de entrada'
        required: true

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
    - name: Validar secret
        env:
          TITLE: ${{ secret.GITHUB }}
        run: |
          if [[ "$TITLE" =~ ^crnic ]]; then
          echo "Token Valido"
          exit 0
          else
          echo "Token INvalido"
          exit 1
          fi
          
    - name: Imprimir mensaje desde reusable-lab.yml
      run: echo "Este es un mensaje desde el flujo de trabajo reusable-lab.yml"

    - name: Usar un secreto
      run: echo "El secreto es ${{ inputs.secreto-entrada }}"
