name: Reusable Workflow

on:
  workflow_call:
    inputs:
      secret-token:
        description: 'Secret token to be used in the workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello from Reusable Workflow! Secret Token: ${{ inputs.secret-token }}"
