name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - name: Imprimir mensaje desde main-workflow.yml
      run: echo "Este es un mensaje desde el flujo de trabajo main-workflow.yml"

    - name: Llamar al flujo de trabajo reusable
      uses: ./.github/workflows/reusable-lab.yml

  main-job-with-secret:
    runs-on: ubuntu-latest
    needs: main-job

    steps:
    - name: Imprimir mensaje secreto desde main-workflow.yml
      run: echo "Mensaje secreto: ${{ secrets.MI_SECRETO }}"
      env:
        MI_SECRETO: ${{ secrets.MI_SECRETO }}

